### ISSUE TITLE
`/f add` does not give feedback on accepting a friend request

### ISSUE THREAD

**Issue by Tuvalu23** [Swift-Strider/QuickFriends#1]
Adding friend does not work

**Comment by Swift-Strider** [comment]
To add a friend you have to `/f add <player`. The other player will get a message saying that they got a friend request.

Next, the other player will have to `/f add <player>` to accept the invitation.

I don't this a bug, but an issue with the UI not giving helpful feedback.

**Comment by Tuvqlu** [comment]
Sorry, I did this through UI and it did not send any feedback, nor did it actually invite the player. Does it only work with commands only?
