### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Tuvalu23** [Swift-Strider/QuickFriends#2]
Where in the code can i edit how the form looks (like changing the lang)? thankyou :D

**Comment by Swift-Strider** [comment]
The code responsible for spawning a form is in the `DiamondStrider1\QuickFriends\Command` namespace, but it's very unreadable. The language in the form is hardcoded, and can't be changed. But anyone's welcome to editing the source for their purposes.

**Comment by Tuvqlu** [comment]
Hmm I’ll try, thankyou
