### ISSUE TITLE
Friending does not work

### ISSUE THREAD

**Issue by Tuvqlu** [Swift-Strider/QuickFriends#3]
If you friend someone and they friend you back, it still says I have 0 friends.

please fix 

- Thankyou :)

**Comment by Swift-Strider** [comment]
What commands have you tried using? And did you get any feedback?

**Comment by Tuvalu23** [comment]
Hello, this works now, however some of the message variable are incorrect

**Comment by Swift-Strider** [comment]
> Hello, this works now, however some of the message variable are incorrect

Can you elaborate?

**Comment by Tuvalu23** [comment]
Like recieved and sender are switched around etc

**Comment by Swift-Strider** [comment]
Which commands have incorrect messages?

**Comment by Tuvalu23** [comment]
Recieved and Sender

**Comment by Swift-Strider** [comment]
Sorry for the delay, but I couldn't recreate this bug. I might have accidentally fixed it already 🙃. If you still use my plugin and encounter this problem on its latest version, feel free to open another issue!
